/**
 * Env template with all NyxMindClaw fields.
 * Used by onboard to generate .env.
 */
export const ENV_TEMPLATE = `# ===== NyxMindClaw — generated by nyxmind onboard =====

# LLM — Supported providers: openai, anthropic, groq, grok, minimax,
#   deepseek, cohere, mistral, perplexity, together, ollama,
#   ollama-cloud, gemini
LLM_PROVIDER=openai
LLM_API_KEY=
LLM_MODEL=
LLM_BASE_URL=

# Agent identity
AGENT_NAME=NyxMindClaw
NODE_ENV=development

# Agent behaviour
MAX_ITERATIONS=10
MEMORY_WINDOW_SIZE=20
LOCALE=en
WORKSPACE=.agents/workspace

# Directories
SKILLS_DIR=.agents/skills
DATA_DIR=./data
TMP_DIR=./tmp

# Database
DATABASE_URL=local

# Security
GLOBAL_ALLOWED_IDS=
MAX_FILE_SIZE=10485760
MAX_AUDIO_SIZE=5242880

# Channels — Discord
DISCORD_ENABLED=false
DISCORD_TOKEN=
DISCORD_GROUP_POLICY=allowlist
DISCORD_RATE_LIMIT=60

# Channels — Telegram
TELEGRAM_ENABLED=false
TELEGRAM_BOT_TOKEN=
TELEGRAM_ALLOWED_IDS=
TELEGRAM_RATE_LIMIT=30

# Channels — WhatsApp
WHATSAPP_ENABLED=false

# Tools
TOOLS_PROFILE=general
WEB_SEARCH_ENABLED=true
WEB_SEARCH_PROVIDER=firecrawl
WEB_FETCH_ENABLED=true

# Telemetry (opt-in)
TELEMETRY_ENABLED=false
TELEMETRY_ENDPOINT=

# Logging
LOG_LEVEL=info
LOG_PRETTY=true
`;