/**
 * Env template with all openclaw-inspired fields.
 * Used by onboard to generate .env.
 */
export const ENV_TEMPLATE = `# ===== NyxMindClaw — generated by nyxmind onboard =====

# LLM
LLM_PROVIDER=openai
LLM_API_KEY=
LLM_MODEL=gpt-4o-mini
LLM_BASE_URL=

# Agent
MAX_ITERATIONS=10
MEMORY_WINDOW_SIZE=20
LOCALE=en
AGENT_NAME=NyxMindClaw
WORKSPACE=.agents/workspace

# Directories
SKILLS_DIR=.agents/skills
DATA_DIR=./data
TMP_DIR=./tmp

# Database
DATABASE_URL=local

# Security
GLOBAL_ALLOWED_IDS=
MAX_FILE_SIZE=10485760
MAX_AUDIO_SIZE=5242880

# Channels — Discord
DISCORD_ENABLED=false
DISCORD_TOKEN=
DISCORD_RATE_LIMIT=60
DISCORD_GROUP_POLICY=allowlist

# Channels — Telegram
TELEGRAM_ENABLED=false
TELEGRAM_BOT_TOKEN=
TELEGRAM_ALLOWED_IDS=
TELEGRAM_RATE_LIMIT=30

# Channels — WhatsApp
WHATSAPP_ENABLED=false

# Telemetry (opt-in)
TELEMETRY_ENABLED=false
TELEMETRY_ENDPOINT=

# Logging
LOG_LEVEL=info
LOG_PRETTY=true

# Node env
NODE_ENV=development
`;
