function mask(v: string): string {
  return v ? '***' : '';
}

export function buildOnboardEnvFile(i: {
  provider: string;
  apiKey: string;
  model: string;
  baseUrl: string;
  maxIterations: string;
  memoryWindow: string;
  skillsDir: string;
  dataDir: string;
  tmpDir: string;
  locale: string;
  whitelist: string;
  maxFileSize: string;
  maxAudioSize: string;
  dbUrl: string;
  tgEnabled: boolean;
  telegramBotToken: string;
  telegramAllowedIds: string;
  telegramRateLimit: string;
  discordEnabled: boolean;
  discordToken: string;
  discordRateLimit: string;
  whatsappEnabled: boolean;
  telemetryEnabled: boolean;
  telemetryEndpoint: string;
  logLevel: string;
}): string {
  const lines: string[] = [
    '# ===== NyxMindClaw — generated by nyxmind onboard =====',
    '',
    '# LLM',
    `LLM_PROVIDER=${i.provider}`,
    `LLM_API_KEY=${mask(i.apiKey)}`,
    `LLM_MODEL=${i.model}`,
    `LLM_BASE_URL=${i.baseUrl}`,
    '',
    '# Agent',
    `MAX_ITERATIONS=${i.maxIterations}`,
    `MEMORY_WINDOW_SIZE=${i.memoryWindow}`,
    `LOCALE=${i.locale}`,
    '',
    '# Directories',
    `SKILLS_DIR=${i.skillsDir}`,
    `DATA_DIR=${i.dataDir}`,
    `TMP_DIR=${i.tmpDir}`,
    '',
    '# Database',
    `DATABASE_URL=${i.dbUrl}`,
    '',
    '# Security',
    `GLOBAL_ALLOWED_IDS=${i.whitelist}`,
    `MAX_FILE_SIZE=${i.maxFileSize}`,
    `MAX_AUDIO_SIZE=${i.maxAudioSize}`,
    '',
    '# Channels',
    `TELEGRAM_ENABLED=${String(i.tgEnabled)}`,
    `TELEGRAM_BOT_TOKEN=${mask(i.telegramBotToken)}`,
    `TELEGRAM_ALLOWED_IDS=${i.telegramAllowedIds}`,
    `TELEGRAM_RATE_LIMIT=${i.telegramRateLimit}`,
    '',
    `DISCORD_ENABLED=${String(i.discordEnabled)}`,
    `DISCORD_TOKEN=${mask(i.discordToken)}`,
    `DISCORD_RATE_LIMIT=${i.discordRateLimit}`,
    '',
    `WHATSAPP_ENABLED=${String(i.whatsappEnabled)}`,
    '',
    '# Telemetry (opt-in)',
    `TELEMETRY_ENABLED=${String(i.telemetryEnabled)}`,
    `TELEMETRY_ENDPOINT=${i.telemetryEndpoint}`,
    '',
    '# Logging',
    `LOG_LEVEL=${i.logLevel}`,
  ];

  return lines.join('\n') + '\n';
}
